DROP DATABASE IF EXISTS `PADEL`;
CREATE DATABASE `PADEL` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
--
-- SELECCIONAMOS PARA USAR
--
USE `PADEL`;
--
-- DAMOS PERMISO USO Y BORRAMOS EL USUARIO QUE QUEREMOS CREAR POR SI EXISTE
--
GRANT USAGE ON * . * TO `PADEL`@`localhost`;
	DROP USER `PADEL`@`localhost`;

--
-- CREAMOS EL USUARIO Y LE DAMOS PASSWORD,DAMOS PERMISO DE USO Y DAMOS PERMISOS SOBRE LA BASE DE DATOS.
--
CREATE USER IF NOT EXISTS `padelUser`@`localhost` IDENTIFIED BY 'padel19';
GRANT USAGE ON *.* TO `padelUser`@`localhost` REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
GRANT ALL PRIVILEGES ON `PADEL`.* TO `padelUser`@`localhost` WITH GRANT OPTION;

CREATE TABLE IF NOT EXISTS USUARIO(

	USERNAME VARCHAR(255),
	PASSWD VARCHAR(255) NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
	AVATAR VARCHAR(255) NOT NULL,
	ROL ENUM('ADMINISTRADOR','DEPORTISTA') NOT NULL,
    SEXO ENUM('HOMBRE', 'MUJER') NOT NULL,
    NIVEL INT NOT NULL,

	CONSTRAINT PK_USUARIO PRIMARY KEY(USERNAME)

)ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;

INSERT INTO USUARIO VALUES('admin','admin','','','','ADMINISTRADOR','',0);